### ISSUE TITLE
why emit this event

### ISSUE THREAD

**Issue by MoonBottle** [k55k32/markdown-it-editor#4]
hello, author 
when i read your code, i find some code like this
```javascript
let success = this.$emit('upload-success', xhr.responseText)
```
so why emit this event in here , because i can't find any useage
thank u

**Comment by k55k32** [comment]
when the image upload success , this emit will be trigger.
See [component-attributes](https://github.com/k55k32/markdown-it-editor#component-attributes) upload props.
if you don't wanna default `upload-success` function execute. 
You can define this emit, and `return false`.
See [Component-Events](https://github.com/k55k32/markdown-it-editor#events)

**Comment by MoonBottle** [comment]
soga, i know ... thanks ~~
