### ISSUE TITLE
err in load preview

### ISSUE THREAD

**Issue by Jack85** [k55k32/markdown-it-editor#5]
Hi, I get when loading in typescript:
tried 1.1.2 and 1.1.4

[Vue warn]: Error in created hook: 
(found in <Preview>)
warn @ vue.common.js:560
handleError @ vue.common.js:1445
window.onload @ app.ts:20
vue.common.js:1449TypeError: Cannot read property 'replace' of undefined
    at Array.e.exports (index.js:2)
    at n.process (index.js:2)
    at i.parse (index.js:1)
    at i.render (index.js:1)

**Comment by k55k32** [comment]
`Cannot read property 'replace' of undefined`
You maybe need find out why throw this error.
I don't know how to write typescript. So my help is limit.  :)

**Comment by Jack85** [comment]
Yes but that error occurs in your control loading preview (stated in warning) missing replace.. you might have idea if I need to set some property or so?

**Comment by k55k32** [comment]
Could you show me your code.
I'll try to look up the error

**Comment by Jack85** [comment]
![image](https://cloud.githubusercontent.com/assets/16955647/24751218/00b3b9e8-1ac9-11e7-8ff9-07b6c09e1ed8.png)

usage>
`  <me v-model="post.Content" ref="me"></me> `



```ts
import { Component, create, getHelper, Vue, Store, Prop, Watch,d, p,Vuex,Lifecycle } from '../../ext1'
import DateTime from "typescript-dotnet-commonjs/System/Time/DateTime"
var multiselect = require('vue-multiselect').default;
//var markdownEditor = require('vue-simplemde').default;
import { MarkdownEditor } from 'markdown-it-editor'
    //var MarkdownEditor = require('markdown-it-editor').default;
import hljs from 'highlightjs' // have to npm install highlight
//import 'highlightjs/styles/github.css'  
    @Component({
        components: { multiselect: multiselect,me:MarkdownEditor }  //multiselect:Multiselect 
        // watch:{ '$route.path': function(newVal?:any, oldVal?:any ){ // this.$route.path:string , newVal?:any, oldVal?:any 
        //      if(this.$route.path!=undefined)
        //      console.log('Changed current path to: ' + this.$route.path);
        //  } } 
    })
    export default class epost extends Vue {
        name = 'editpost'
        id = name;
        mode = 'insert'

      //  mselected = [];
      //  options = ['polo', 'trans', 'golf','jaguar', 'a6', 'tiguan', 'kadjar','ateca']; 

        post:d.Post = new d.Post();
        cats:d.Category[] =[] ;
        tags:d.Tag[] = [];
        
        saved:boolean =false;

          options= {
        highlight (str, lang) { // you can add highlightjs plugin to highlight your code
          if (lang && hljs.getLanguage(lang)) {
            try {
              return hljs.highlight(lang, str).value
            } catch (__) {}
          }
          return '';
        }};
}
```
maybe its options problem, but this should work i believe

**Comment by Jack85** [comment]
It was content that was initialized in mounted. 
Functionality is there, now I have only problems to load css, i need to check.

**Comment by Jack85** [comment]
this one was missing in quick guide
import './../node_modules/markdown-it-editor/lib/css/iconfont.b300b13.woff'
