### ISSUE TITLE
I only want to render the source, how to do it ?

### ISSUE THREAD

**Issue by talliujobs** [k55k32/markdown-it-editor#6]
Hi, this is a useful component. 
Now I only want to render the source , is there a way to do this?

**Comment by k55k32** [comment]
I split the `MarkdownPreview`  component . you can use that.
```js
import { MarkdownPreview } from 'markdown-it-editor'
```
the componet detail see the [MarkdownPreview.vue](https://github.com/k55k32/markdown-it-editor/blob/master/src/components/MarkdownPreview.vue)
